### ISSUE TITLE
setOrderReferenceDetails example?

### ISSUE THREAD

**Issue by QuinDennis** [MadisonReed/amazon-payments#6]
Greetings!
Glad I found your work.  I'm through getTokenInfo, getProfile, working on Creating an order (for an item on our site), then Authorize and Capture.  Below is creating an order, but there is an error.  I'm not even sure how to debug this, being on the AWS end, and they don't appear to do javascript / node.  Your package is perfect for what we need.  And I think we're very close!

function createOrder() {
    var attrs = {
        AmazonOrderReferenceId:'arfid',
        Amount:'10',
        OrderReferenceAttribtues:{
            OrderTotal:{
                Amount:'10',
                CurrencyCode:'USD'
            },
            SellerNote:'A Seller Note',
            SellerOrderAttributes:{
                SellerOrderId:'123abc',
               StoreName:'Thinking-By-Ear.com'
            }
        }
    }
    payment.offAmazonPayments.setOrderReferenceDetails(attrs, function(err) {
        console.log(err)
    })
}

////// ERROR RESPONSE
{ [InvalidParameterValue: 1 validation error detected: Value null at 'orderReferenceAttributes' failed to satisfy constraint: Member must not be null]
  type: 'InvalidParameterValue',
  name: 'InvalidParameterValue',
  body:
   { ErrorResponse:
      { '$': [Object],
        Error: [Object],
        RequestId: '5c0da6f5-6a33-40a2-a9af-df080c57f882' } } }

**Comment by divesnob** [comment]
Thanks for the feedback.  We'll look into this, and if necessary update the module with a fix.
@scottspork

**Comment by scottspork** [comment]
The only issue that I can see is that you're including `Amount` on the top level and under `OrderTotal`. According to the [documentation](https://payments.amazon.com/documentation/apireference/201751960) `Amount` should only be included under `OrderTotal`.
