### ISSUE TITLE
Need to replace * with %2A in text

### ISSUE THREAD

**Issue by LasCondes** [MadisonReed/amazon-payments#8]
I like you library. Much simpler than what I was trying to use. One issue has come up.

If I send

  "SellerCaptureNote": "Payment for Standard \* Subscription",

to Capture I get the following error from Amazon

  "errorMessage": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.",
  "errorType": "SignatureDoesNotMatch"

If I remove the \* it works.

How best to replace \* with %2A ?

**Comment by divesnob** [comment]
Thanks - appreciated the feedback.

I'll get an update made so that we url-encode those params before the
signature is calculated.

MATT DARLING

—

VP Engineering

Phone: 415.505.4623

Social: @MadisonReedLLB

Madison-Reed.com http://www.madison-reed.com/

MADISONREED®

**Comment by scottspork** [comment]
This is fixed in pull request #9. The fix will be present in version 0.2.4 of the npm module.
